spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: affable-bean-backend
            uri: lb://affable-bean-backend
            predicates:
              - Path=/api/affableBean/**

          - id: affable-bean-ui
            uri: lb://affable-bean-ui
            predicates:
              - Path=/ui/affableBean/**, /bootstrap/**, /images/**

          - id: payment-gateway
            uri: lb://payment-gateway
            predicates:
              - Path=/api/payment/**
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka