spring:
  application:
    name: gateway-demo
  cloud:
    gateway:
      mvc:
        routes:
          - id: CounterService
            uri: lb://COUNTER-SERVICE
            predicates:
              - Path=/counter/**
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
